### ISSUE TITLE
Historic runs apparently aren't parsed when reprocessing...

### ISSUE THREAD

**Issue by mibj01** [jenkinsci/build-time-blame-plugin#9] opened 2017-05-23 12:29 UTC
Hi!

Just included this great plug-in as part of our build pipeline and already seen a number of places where we can fine-tune it.

The problem I have is that whenever I extend the ruleset or re-runs the logging process the only build that shows up in the graph and tables are the absolutely last one. All the historic data is gone.

Is there something I have missed in the setup or is this a "feature"/"bug"?

Thanks for a great plug-in!

/Mikael

**Comment by LTegtmeier** [comment] 2017-05-23 12:35
Thanks!

Only builds that ran while the timestamps were enabled can show up in the report.  Did the graph ever show data for these builds?

**Comment by mibj01** [comment] 2017-05-23 12:45
Yes... they did... I probably got three consecutive builds showing and then suddenly only the latest...

**Comment by LTegtmeier** [comment] 2017-05-23 12:52
Are the builds still there with visible console logs and timestamps? If so, can you attach screenshots and/or a zip of the builds directory for the job so I can troubleshoot it?

**Comment by mibj01** [comment] 2017-05-23 13:11
Yes, they are...  I can go through them and look at the timestamps without any problems...

These are screenshots from the builds that has timestamps on them... as well as the report page.

Thanks for the help!

/Mikael

![reoport](https://cloud.githubusercontent.com/assets/1239632/26355690/e86ccec6-3fc9-11e7-873f-1769914a9ee1.png)
![console log 3687](https://cloud.githubusercontent.com/assets/1239632/26355693/e87bbcba-3fc9-11e7-942d-a7bb5a9146ba.png)
![console log 3682](https://cloud.githubusercontent.com/assets/1239632/26355691/e86cf748-3fc9-11e7-82e5-e04bfcb5e95e.png)
![console log 3688](https://cloud.githubusercontent.com/assets/1239632/26355692/e86e034a-3fc9-11e7-9d5e-e9340c72f205.png)

**Comment by LTegtmeier** [comment] 2017-05-23 13:23
And if you run another build and just load the report page, do you get results for 3688 and 3689? But, if you reprocess the report you will only get 3689?

**Comment by mibj01** [comment] 2017-05-23 13:26
If I run another build I get a second data point on the report but that disappears when I do a reprocess which leaves me with only the latest build...

**Comment by LTegtmeier** [comment] 2017-05-24 20:49
I'm not sure how this would happen since the plugin should attempt to parse logs for all builds that are not running and successful. If there are errors, it would print the failed builds at the top of the screen. Can you give me the following information to try to recreate/debug this?

1. Jenkins version
1. Timestamper plugin version
1. Does this happen for other jobs or just this one?
1. In JENKINS_HOME on the master there should be `/jobs/express-mainline-build/builds` Can you send me the log file and the timestamper folder from a build number that is showing in the report and for a a build number that no longer shows in the report?

**Comment by LTegtmeier** [comment] 2017-05-31 18:28
@mibj01, any response to the questions above?

**Comment by LTegtmeier** [comment] 2017-06-05 13:58
Closing until it is reproducible

**Comment by Nuxij** [comment] 2017-11-24 11:37
This happened to me today. It didn't happen on every reprocess, I put it down to the fact I had actually removed some regex patterns, assuming it was ignoring the history now my report query was sufficiently different (or something whacky like that) - maybe the removal of a regex is the repro key, don't know.

**Comment by LTegtmeier** [comment] 2017-11-25 04:24
I'll try to find time to look into that. When the report is reprocessed it **should** start completely from scratch and process all successful builds. If a particular build has **no** matches, ~~I think it would be exempt from the report.~~  It still shows in the graph but, does not impact the averages.

**Comment by LTegtmeier** [comment] 2017-12-20 04:20
@Joeasaurus or @mibj01, can you answer [the questions above](https://github.com/jenkinsci/build-time-blame-plugin/issues/9#issuecomment-303847613) and/or provide the build directory for a job or some minimal example where this is happening?

**Comment by LTegtmeier** [comment] 2017-12-20 04:34
Looking again, I can recreate this on my test instance. Still not sure why it happens yet. But, I should be able to clean it up

**Closed as completed** 2018-01-02 03:38 UTC

**Comment by LTegtmeier** [comment] 2018-01-02 15:20
Fixes were released in v1.1.2
